### ISSUE TITLE
example of config JSON usage 

### ISSUE THREAD

**Issue by JuanCarlos-Arceredillo** [AppiumTestDistribution/appium-wait-plugin#42]
Hi,

Could you show how to initialize the appium server with this plugin using the config json file of the docs ?

Thank you

**Comment by saikrishna321** [comment]
Please refer this https://github.com/AppiumTestDistribution/appium-device-farm/blob/main/server-config.json

You need to change the plug-in name to 'element-wait'

**Comment by JuanCarlos-Arceredillo** [comment]
Hi @saikrishna321 ,

Thank you for this information. My question is more related to how to set to appium that it should use this json file. 

Do we need to place this file in a specific path ? or, Has appium got an argument to set that it has to read this file ?

**Comment by saikrishna321** [comment]
appium server -ka 800 --config pathtothefile/server-config.json -pa /wad/hub

**Comment by JuanCarlos-Arceredillo** [comment]
Thank you for the information @saikrishna321
