### ISSUE TITLE
Not able to activate the plugin after installing via NPM

### ISSUE THREAD

**Issue by rarkasa** [AppiumTestDistribution/appium-wait-plugin#49]
I installed the package via NPM, but when I am running **appium --use-plugins=element-wait** in the command line get's an error as
**error: unrecognized arguments: --use-plugins=element-wait**

Seems like there's no --use-plugins option in Appium

**Comment by saikrishna321** [comment]
Please use the latest appium server version.

appium server --use-plugins=element-wait

**Comment by rarkasa** [comment]
I am using 1.22.3, but still getting the same error when I run **appium server --use-plugins=element-wait**
<img width="573" alt="Screen Shot 2022-10-14 at 12 08 13 pm" src="https://user-images.githubusercontent.com/113505072/195740114-f50f0f27-7f9f-4831-9670-4056602ac5e5.png">

![Screen Shot 2022-10-14 at 12 08 53 pm](https://user-images.githubusercontent.com/113505072/195740135-4940ed1d-af14-4f85-a92b-2af8e8f2c896.png)

**Comment by saikrishna321** [comment]
You should use appium 2.x version
