### ISSUE TITLE
Unable to install appium-wait-plugin

### ISSUE THREAD

**Issue by paruladhikari-helpshift** [AppiumTestDistribution/appium-wait-plugin#69]
Upon running the command : appium plugin install --source=npm appium-wait-plugin I am getting the following error:

`
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@8.6.0
2 info using node@v16.13.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/xx/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 8ms
18 timing npm:load:configload Completed in 8ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm install appium-wait-plugin
22 verbose argv "install" "--save-dev" "appium-wait-plugin" "--json"
23 timing npm:load:setTitle Completed in 17ms
24 timing config:load:flatten Completed in 2ms
25 timing npm:load:display Completed in 3ms
26 verbose logfile logs-max:10 dir:/Users/xx/.npm/_logs
27 verbose logfile /Users/xx/.npm/_logs/2023-04-04T14_08_44_164Z-debug-0.log
28 timing npm:load:logFile Completed in 5ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 36ms
32 timing arborist:ctor Completed in 0ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 919ms
36 timing idealTree:userRequests Completed in 2ms
37 silly idealTree buildDeps
38 silly fetch manifest appium-wait-plugin@*
39 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules/@appium
40 http fetch GET 200 https://registry.npmjs.org/appium-wait-plugin 395ms (cache hit)
41 silly fetch manifest appium@^1.9.1
42 http fetch GET 200 https://registry.npmjs.org/appium 913ms (cache hit)
43 silly fetch manifest appium@^2.0.0-beta.57
44 timing idealTree Completed in 2247ms
45 timing command:install Completed in 2257ms
46 verbose stack Error: unable to resolve dependency tree
46 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1418:25)
46 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1384:34)
46 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:970:11)
46 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
46 verbose stack     at async Promise.all (index 1)
46 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
46 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:159:5)
46 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
47 verbose cwd /Users/xx
48 verbose Darwin 22.2.0
49 verbose node v16.13.2
50 verbose npm  v8.6.0
51 error code ERESOLVE
52 error ERESOLVE unable to resolve dependency tree
53 error
54 error While resolving: parul@1.0.0
54 error Found: appium@1.22.3
54 error node_modules/appium
54 error   appium@"^1.9.1" from the root project
54 error
54 error Could not resolve dependency:
54 error peer appium@"^2.0.0-beta.57" from appium-wait-plugin@1.2.0
54 error node_modules/appium-wait-plugin
54 error   dev appium-wait-plugin@"*" from the root project
54 error
54 error Fix the upstream dependency conflict, or retry
54 error this command with --force, or --legacy-peer-deps
54 error to accept an incorrect (and potentially broken) dependency resolution.
54 error
"~/.npm/_logs/2023-04-04T14_08_44_164Z-debug-0.log" 86L, 4706B
`

The Appium version installed on my machine: appium --version
2.0.0-beta.59

**Comment by saikrishna321** [comment]
Unable to reproduce
