### ISSUE TITLE
find element not working for iOS platform while using element-wait@1.2.0 plugin  

### ISSUE THREAD

**Issue by sushilpawar12** [AppiumTestDistribution/appium-wait-plugin#70]
command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["element-wait"].
[debug] [XCUITestDriver@1963 (f9b46943)] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'jwproxy')

Appium v - 2.0.0-beta.65 , xcuitest@4.24.2 , element-wait@1.2.0

**Comment by saikrishna321** [comment]
@sushilpawar12 Thanks for reporting. Will look into this.

**Comment by saikrishna321** [comment]
@sushilpawar12 Please try with latest version
